# Название workflow для запуска тестов
name: Run Tests with Mock Server

# Триггеры для запуска workflow
on:
  workflow_dispatch: # Для ручного запуска
  push:
    branches: [ master ]  # Запуск при пуше в ветку master
  pull_request:
    branches: [ master ]  # Запуск при создании PR в ветку master

# Определение job'ы тестирования
jobs:
  test:
    # Запуск на последней версии Ubuntu
    runs-on: ubuntu-latest

    # Определение сервисов, необходимых для job'ы
    services:
      # Сервис мок-сервера
      mock-server:
        # Использование образа из GitHub Container Registry
        image: ghcr.io/stasnislav121/example-mock-server:main
        # Проброс порта 8000 из контейнера на хост
        ports:
          - 8000:8000
        # Настройка healthcheck для контейнера
        options: >-
          --health-cmd "curl -f http://localhost:8000/health || exit 1"
          --health-interval=5s
          --health-timeout=3s
          --health-start-period=10s
          --health-retries=10

    # Шаги выполнения job'ы
    steps:
    # Шаг 1: Получение кода автотестов
    - uses: actions/checkout@v4

    # Шаг 2: Установка Python
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'  # Указание версии Python

    # Шаг 3: Установка зависимостей для тестов
    - name: Install dependencies
      run: |
        # Обновление pip до последней версии
        python -m pip install --upgrade pip
        # Установка зависимостей из requirements.txt
        pip install -r requirements.txt
        pip install -r requirements-api.txt

    # Шаг 4: Ожидание готовности мок-сервера
    - name: Wait for mock server
      run: |
        # Попытка подключения к мок-серверу в течение 10 попыток
        for i in {1..10}; do
          # Проверка доступности эндпоинта здоровья
          if curl -s http://localhost:8000/health > /dev/null; then
            echo "Mock server is ready!"
            break
          fi
          echo "Waiting for mock server... ($i/10)"
          sleep 5  # Ожидание 5 секунд между попытками
        done

    # Шаг 5: Запуск тестов
    - name: Run tests
      id: run-tests
      env:
        # Установка переменной окружения с базовым URL API
        API_BASE_URL: "http://localhost:8000"
      run: |
        # Запускаем тесты и сохраняем вывод
        pytest -m "forci" --alluredir=./allure-results -v > test-output.txt 2>&1
        exit_code=$?
        
        # Выводим содержимое файла для отладки
        echo "=== TEST OUTPUT ==="
        cat test-output.txt
        echo "==================="
        
        # Извлекаем статистику тестов более надежным способом
        # Ищем строку с результатами в конце вывода
        TEST_RESULTS=$(tail -20 test-output.txt | grep -E "(passed|failed|skipped|deselected)" | tail -1)
        
        # Извлекаем числа с помощью awk
        PASSED_TESTS=$(echo "$TEST_RESULTS" | awk '{for(i=1;i<=NF;i++)if($i~/passed/ && $(i-1)~/^[0-9]+$/)print $(i-1)}' | head -1)
        FAILED_TESTS=$(echo "$TEST_RESULTS" | awk '{for(i=1;i<=NF;i++)if($i~/failed/ && $(i-1)~/^[0-9]+$/)print $(i-1)}' | head -1)
        SKIPPED_TESTS=$(echo "$TEST_RESULTS" | awk '{for(i=1;i<=NF;i++)if($i~/skipped/ && $(i-1)~/^[0-9]+$/)print $(i-1)}' | head -1)
        DESELECTED_TESTS=$(echo "$TEST_RESULTS" | awk '{for(i=1;i<=NF;i++)if($i~/deselected/ && $(i-1)~/^[0-9]+$/)print $(i-1)}' | head -1)
        
        # Устанавливаем значения по умолчанию, если не найдены
        PASSED_TESTS=${PASSED_TESTS:-0}
        FAILED_TESTS=${FAILED_TESTS:-0}
        SKIPPED_TESTS=${SKIPPED_TESTS:-0}
        DESELECTED_TESTS=${DESELECTED_TESTS:-0}
        
        # Вычисляем общее количество тестов
        TOTAL_TESTS=$((PASSED_TESTS + FAILED_TESTS + SKIPPED_TESTS))
        
        # Сохраняем статистику в output
        echo "total_tests=$TOTAL_TESTS" >> $GITHUB_OUTPUT
        echo "passed_tests=$PASSED_TESTS" >> $GITHUB_OUTPUT
        echo "failed_tests=$FAILED_TESTS" >> $GITHUB_OUTPUT
        echo "skipped_tests=$SKIPPED_TESTS" >> $GITHUB_OUTPUT
        echo "deselected_tests=$DESELECTED_TESTS" >> $GITHUB_OUTPUT
        echo "exit_code=$exit_code" >> $GITHUB_OUTPUT
        
        # Всегда возвращаем успешный код выхода, чтобы workflow продолжился
        exit 0

    - name: Install Allure CLI manually
      run: |
        mkdir -p $HOME/allure
        cd $HOME/allure
        curl -o allure-2.24.0.tgz -Ls https://github.com/allure-framework/allure2/releases/download/2.24.0/allure-2.24.0.tgz
        tar -zxvf allure-2.24.0.tgz
        echo "$HOME/allure/allure-2.24.0/bin" >> $GITHUB_PATH
        $HOME/allure/allure-2.24.0/bin/allure --version

    - name: Generate Allure report
      if: always()
      run: |
        $HOME/allure/allure-2.24.0/bin/allure generate ./allure-results -o ./allure-report --clean

    - name: Check generated report
      run: |
        echo "Contents of allure-report directory:"
        ls -la ./allure-report/
        echo "Index.html exists:"
        test -f ./allure-report/index.html && echo "YES" || echo "NO"

    - name: Deploy to GitHub Pages
      if: always()
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./allure-report
        keep_files: false

    - name: Upload Allure results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: allure-results
        path: allure-results

    - name: Send Telegram notification
      if: always()
      run: |
        # Определяем эмодзи в зависимости от статуса тестов
        if [ "${{ steps.run-tests.outputs.exit_code }}" = "0" ]; then
          EMOJI="✅"
          STATUS_TEXT="Успешно"
        else
          EMOJI="❌"
          STATUS_TEXT="С ошибками"
        fi
        
        # Формируем сообщение для Telegram
        MESSAGE="$EMOJI *Результаты тестирования* $EMOJI%0A%0A"
        MESSAGE+="*Репозиторий:* \`${{ github.repository }}\`%0A"
        MESSAGE+="*Статус:* $STATUS_TEXT%0A"
        MESSAGE+="*Ветка:* ${{ github.ref_name }}%0A"
        MESSAGE+="*Коммит:* [${GITHUB_SHA:0:7}](https://github.com/${{ github.repository }}/commit/${{ github.sha }})%0A%0A"
        MESSAGE+="*📊 Статистика тестов:*%0A"
        MESSAGE+="• Всего тестов: ${{ steps.run-tests.outputs.total_tests }}%0A"
        MESSAGE+="• ✅ Успешных: ${{ steps.run-tests.outputs.passed_tests }}%0A"
        MESSAGE+="• ❌ Проваленных: ${{ steps.run-tests.outputs.failed_tests }}%0A"
        MESSAGE+="• ⏩ Пропущенных: ${{ steps.run-tests.outputs.skipped_tests }}%0A"
        MESSAGE+="• 🔶 Исключенных: ${{ steps.run-tests.outputs.deselected_tests }}%0A%0A"
        MESSAGE+="*📝 Отчет Allure:* [Посмотреть отчет](https://stasnislav121.github.io/Example_tests/)%0A"
        MESSAGE+="*🔍 Детали запуска:* [Посмотреть запуск](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }})"
        
        # Отправляем сообщение в Telegram
        curl -s -X POST "https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage" \
          -d chat_id="${{ secrets.TELEGRAM_CHAT_ID }}" \
          -d parse_mode="Markdown" \
          -d text="$MESSAGE"

    - name: Cleanup
      run: |
        docker stop mock-server || true
        docker rm mock-server || true
